### ISSUE TITLE
Fixing issues for blog post readers

### ISSUE THREAD

**Issue by hangler** [mongodb-developer/cloudflare-worker-rest-api-realm-atlas#14]
First and foremost, thanks for [your great tutorial](https://www.mongodb.com/developer/products/atlas/cloudflare-worker-rest-api), which led me here.

I was able to follow it quite smoothly, despite a couple of deprecation warnings when deploying to Cloudflare, but in the end my project wasn’t working properly. Specifically, I couldn’t POST using the shell scripts you provide in `/api_tests`.

I did get it fixed, and had to do two things:

1) Apply the code updates in this PR: https://github.com/mongodb-developer/cloudflare-worker-rest-api-atlas/pull/10 (fixes the deprecation warnings upon deploy, too).

2) Change the collection rule to be `{"owner": "%%user.id"}` (i.e. adding the `%%` for the expansion, which I suppose may now be required since the time the article was written).

With those changes, it’s working great. So, I just thought I’d write this in case you get a chance to update the blog post. (I do notice you've made the `%%` change in the README to this project, but that wasn't immediately clear to me.)

Thanks again!

**Comment by MaBeuLux88** [comment]
Thanks for the fix :+1: @hangler.
Now we have a new ReadOwnWriteOwn preset in Atlas App Services rules that basically does the same thing automatically. I just had to rename `owner` to `owner_id` though. 
I updated the blog post accordingly :+1: 

Cheers, 
Maxime.
