### ISSUE TITLE
Store authentication on Durable Object

### ISSUE THREAD

**Issue by leomp12** [mongodb-developer/cloudflare-worker-rest-api-realm-atlas#3]
Hello,

CF Workers Durable Object is now [general available]( https://blog.cloudflare.com/durable-objects-ga/) and I think using it to store Realm app user would improve performance considerably, am I right?

> And what about connecting worker to [Data API](https://docs.atlas.mongodb.com/api/data-api/)? May be better (faster) solution? What do you recommend after the _preview_ phase?

**Comment by MaBeuLux88** [comment]
Hi @leomp12,

Technically speaking, caching the app user could improve the performances a bit, but it generates a bunch of new problems that aren't trivial to solve.
- how do you know when you have to refresh the cache and regenerate a new user object?
- how can you ensure that you are giving the right user object to the right Worker client? If you give the wrong user to the wrong client, you are most likely giving them access to documents or collections they shouldn't have access to.
- how do you know when a user's rights have been updated in Realm? Also maybe the user could have been removed entirely and shouldn't have access anymore. Realm will deny the query anyway, but this means that you need some more defensive code in case something goes wrong.

Regarding the new Data API, I don't see the point of adding a Worker between your front end and your Data API which can act as a backend system.
[MongoDB Realm Functions](https://docs.mongodb.com/realm/functions/) and the [SDKs](https://docs.mongodb.com/realm/sdk/) are still a better option (better integration and already a connection pool with Atlas) so I guess it's still a better option.

**Comment by leomp12** [comment]
Ok, got it, would be really nice if we can deploy Realm apps to other regions.
Thanks!

> About Worker between frontend and Data API, is to handle rate limiting, authentication, etc...

**Comment by MaBeuLux88** [comment]
Realm is limited to these 7 "main" regions for now: https://docs.mongodb.com/realm/manage-apps/deploy/deployment-models-and-regions/. 
But I guess we can expect more in the future.

**Comment by leomp12** [comment]
Yep @MaBeuLux88 , I got to see, in my case it was necessary to deploy in South America so Realm wouldn't solve yet...
Thanks again!
