### ISSUE TITLE
Returns an empty Array

### ISSUE THREAD

**Issue by ghost** [mongodb-developer/cloudflare-worker-rest-api-realm-atlas#4]
Hello,
I have no idea why it's not working, I'm getting a 200 status code and the Auth is OK.

I've inserted something into the collection but it show an empty array.

**Comment by MaBeuLux88** [comment]
Hi Damian,

Realm filters the documents automatically according to the rule you have set. So for example if you have the rule "users can read and write only there own documents", it's going to filter by the user field that you have set and you can only see these documents where userid == the userid of your currently logged in user sending the query.

When you write the document, make sure that you are writing the userid = user.id as well so you can match later on it.

In my example in the [blog post](https://www.mongodb.com/developer/how-to/cloudflare-worker-rest-api-realm/), my field is `owner`.

Cheers!
Maxime

**Comment by ghost** [comment]
That was the issue I had, thanks, it worked when I used post.sh and then findAll.sh

**Comment by MaBeuLux88** [comment]
Notice that when you are using post.sh, it's calling [this part of the code](https://github.com/mongodb-developer/cloudflare-worker-rest-api-realm-atlas/blob/fac458d5d45ca07bbb7c40c0b337a8447839dd04/src/index.ts#L70).

And as you can see [here](https://github.com/mongodb-developer/cloudflare-worker-rest-api-realm-atlas/blob/fac458d5d45ca07bbb7c40c0b337a8447839dd04/src/index.ts#L74), I'm setting the `owner` to `user.id` to make sure that this todo belongs to the current user.
